/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StartRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartRequest{}

// StartRequest struct for StartRequest
type StartRequest struct {
	// Task scope for this specific run (Session.prompt)
	Prompt *string `json:"prompt,omitempty"`
}

// NewStartRequest instantiates a new StartRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartRequest() *StartRequest {
	this := StartRequest{}
	return &this
}

// NewStartRequestWithDefaults instantiates a new StartRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartRequestWithDefaults() *StartRequest {
	this := StartRequest{}
	return &this
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *StartRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *StartRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *StartRequest) SetPrompt(v string) {
	o.Prompt = &v
}

func (o StartRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	return toSerialize, nil
}

type NullableStartRequest struct {
	value *StartRequest
	isSet bool
}

func (v NullableStartRequest) Get() *StartRequest {
	return v.value
}

func (v *NullableStartRequest) Set(val *StartRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartRequest(val *StartRequest) *NullableStartRequest {
	return &NullableStartRequest{value: val, isSet: true}
}

func (v NullableStartRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
