/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CredentialTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialTokenResponse{}

// CredentialTokenResponse struct for CredentialTokenResponse
type CredentialTokenResponse struct {
	// ID of the credential
	CredentialId string `json:"credential_id"`
	// Provider type for this credential
	Provider string `json:"provider"`
	// Decrypted token value
	Token string `json:"token"`
}

type _CredentialTokenResponse CredentialTokenResponse

// NewCredentialTokenResponse instantiates a new CredentialTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialTokenResponse(credentialId string, provider string, token string) *CredentialTokenResponse {
	this := CredentialTokenResponse{}
	this.CredentialId = credentialId
	this.Provider = provider
	this.Token = token
	return &this
}

// NewCredentialTokenResponseWithDefaults instantiates a new CredentialTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialTokenResponseWithDefaults() *CredentialTokenResponse {
	this := CredentialTokenResponse{}
	return &this
}

// GetCredentialId returns the CredentialId field value
func (o *CredentialTokenResponse) GetCredentialId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value
// and a boolean to check if the value has been set.
func (o *CredentialTokenResponse) GetCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialId, true
}

// SetCredentialId sets field value
func (o *CredentialTokenResponse) SetCredentialId(v string) {
	o.CredentialId = v
}

// GetProvider returns the Provider field value
func (o *CredentialTokenResponse) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CredentialTokenResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CredentialTokenResponse) SetProvider(v string) {
	o.Provider = v
}

// GetToken returns the Token field value
func (o *CredentialTokenResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CredentialTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CredentialTokenResponse) SetToken(v string) {
	o.Token = v
}

func (o CredentialTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential_id"] = o.CredentialId
	toSerialize["provider"] = o.Provider
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *CredentialTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential_id",
		"provider",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialTokenResponse := _CredentialTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialTokenResponse)

	if err != nil {
		return err
	}

	*o = CredentialTokenResponse(varCredentialTokenResponse)

	return err
}

type NullableCredentialTokenResponse struct {
	value *CredentialTokenResponse
	isSet bool
}

func (v NullableCredentialTokenResponse) Get() *CredentialTokenResponse {
	return v.value
}

func (v *NullableCredentialTokenResponse) Set(val *CredentialTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialTokenResponse(val *CredentialTokenResponse) *NullableCredentialTokenResponse {
	return &NullableCredentialTokenResponse{value: val, isSet: true}
}

func (v NullableCredentialTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
