/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectHome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectHome{}

// ProjectHome struct for ProjectHome
type ProjectHome struct {
	ProjectId *string            `json:"project_id,omitempty"`
	Agents    []ProjectHomeAgent `json:"agents,omitempty"`
}

// NewProjectHome instantiates a new ProjectHome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectHome() *ProjectHome {
	this := ProjectHome{}
	return &this
}

// NewProjectHomeWithDefaults instantiates a new ProjectHome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectHomeWithDefaults() *ProjectHome {
	this := ProjectHome{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectHome) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHome) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectHome) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ProjectHome) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetAgents returns the Agents field value if set, zero value otherwise.
func (o *ProjectHome) GetAgents() []ProjectHomeAgent {
	if o == nil || IsNil(o.Agents) {
		var ret []ProjectHomeAgent
		return ret
	}
	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHome) GetAgentsOk() ([]ProjectHomeAgent, bool) {
	if o == nil || IsNil(o.Agents) {
		return nil, false
	}
	return o.Agents, true
}

// HasAgents returns a boolean if a field has been set.
func (o *ProjectHome) HasAgents() bool {
	if o != nil && !IsNil(o.Agents) {
		return true
	}

	return false
}

// SetAgents gets a reference to the given []ProjectHomeAgent and assigns it to the Agents field.
func (o *ProjectHome) SetAgents(v []ProjectHomeAgent) {
	o.Agents = v
}

func (o ProjectHome) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectHome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Agents) {
		toSerialize["agents"] = o.Agents
	}
	return toSerialize, nil
}

type NullableProjectHome struct {
	value *ProjectHome
	isSet bool
}

func (v NullableProjectHome) Get() *ProjectHome {
	return v.value
}

func (v *NullableProjectHome) Set(val *ProjectHome) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectHome) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectHome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectHome(val *ProjectHome) *NullableProjectHome {
	return &NullableProjectHome{value: val, isSet: true}
}

func (v NullableProjectHome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectHome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
