/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the InboxMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InboxMessage{}

// InboxMessage struct for InboxMessage
type InboxMessage struct {
	Id        *string    `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	Href      *string    `json:"href,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Recipient — the agent address
	AgentId string `json:"agent_id"`
	// Sender Agent id — null if sent by a human
	FromAgentId *string `json:"from_agent_id,omitempty"`
	// Denormalized sender display name
	FromName *string `json:"from_name,omitempty"`
	Body     string  `json:"body"`
	// false = unread; drained at session start
	Read *bool `json:"read,omitempty"`
}

type _InboxMessage InboxMessage

// NewInboxMessage instantiates a new InboxMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInboxMessage(agentId string, body string) *InboxMessage {
	this := InboxMessage{}
	this.AgentId = agentId
	this.Body = body
	return &this
}

// NewInboxMessageWithDefaults instantiates a new InboxMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboxMessageWithDefaults() *InboxMessage {
	this := InboxMessage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InboxMessage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InboxMessage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InboxMessage) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *InboxMessage) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *InboxMessage) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *InboxMessage) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *InboxMessage) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *InboxMessage) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *InboxMessage) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *InboxMessage) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *InboxMessage) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *InboxMessage) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *InboxMessage) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *InboxMessage) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *InboxMessage) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetAgentId returns the AgentId field value
func (o *InboxMessage) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *InboxMessage) SetAgentId(v string) {
	o.AgentId = v
}

// GetFromAgentId returns the FromAgentId field value if set, zero value otherwise.
func (o *InboxMessage) GetFromAgentId() string {
	if o == nil || IsNil(o.FromAgentId) {
		var ret string
		return ret
	}
	return *o.FromAgentId
}

// GetFromAgentIdOk returns a tuple with the FromAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetFromAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromAgentId) {
		return nil, false
	}
	return o.FromAgentId, true
}

// HasFromAgentId returns a boolean if a field has been set.
func (o *InboxMessage) HasFromAgentId() bool {
	if o != nil && !IsNil(o.FromAgentId) {
		return true
	}

	return false
}

// SetFromAgentId gets a reference to the given string and assigns it to the FromAgentId field.
func (o *InboxMessage) SetFromAgentId(v string) {
	o.FromAgentId = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *InboxMessage) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *InboxMessage) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *InboxMessage) SetFromName(v string) {
	o.FromName = &v
}

// GetBody returns the Body field value
func (o *InboxMessage) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *InboxMessage) SetBody(v string) {
	o.Body = v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *InboxMessage) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessage) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *InboxMessage) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *InboxMessage) SetRead(v bool) {
	o.Read = &v
}

func (o InboxMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InboxMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["agent_id"] = o.AgentId
	if !IsNil(o.FromAgentId) {
		toSerialize["from_agent_id"] = o.FromAgentId
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	toSerialize["body"] = o.Body
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	return toSerialize, nil
}

func (o *InboxMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInboxMessage := _InboxMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInboxMessage)

	if err != nil {
		return err
	}

	*o = InboxMessage(varInboxMessage)

	return err
}

type NullableInboxMessage struct {
	value *InboxMessage
	isSet bool
}

func (v NullableInboxMessage) Get() *InboxMessage {
	return v.value
}

func (v *NullableInboxMessage) Set(val *InboxMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableInboxMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableInboxMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboxMessage(val *InboxMessage) *NullableInboxMessage {
	return &NullableInboxMessage{value: val, isSet: true}
}

func (v NullableInboxMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboxMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
