/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InboxMessagePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InboxMessagePatchRequest{}

// InboxMessagePatchRequest struct for InboxMessagePatchRequest
type InboxMessagePatchRequest struct {
	Read *bool `json:"read,omitempty"`
}

// NewInboxMessagePatchRequest instantiates a new InboxMessagePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInboxMessagePatchRequest() *InboxMessagePatchRequest {
	this := InboxMessagePatchRequest{}
	return &this
}

// NewInboxMessagePatchRequestWithDefaults instantiates a new InboxMessagePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboxMessagePatchRequestWithDefaults() *InboxMessagePatchRequest {
	this := InboxMessagePatchRequest{}
	return &this
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *InboxMessagePatchRequest) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxMessagePatchRequest) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *InboxMessagePatchRequest) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *InboxMessagePatchRequest) SetRead(v bool) {
	o.Read = &v
}

func (o InboxMessagePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InboxMessagePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	return toSerialize, nil
}

type NullableInboxMessagePatchRequest struct {
	value *InboxMessagePatchRequest
	isSet bool
}

func (v NullableInboxMessagePatchRequest) Get() *InboxMessagePatchRequest {
	return v.value
}

func (v *NullableInboxMessagePatchRequest) Set(val *InboxMessagePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInboxMessagePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInboxMessagePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboxMessagePatchRequest(val *InboxMessagePatchRequest) *NullableInboxMessagePatchRequest {
	return &NullableInboxMessagePatchRequest{value: val, isSet: true}
}

func (v NullableInboxMessagePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboxMessagePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
