// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 97773951f427a0271532ec5ed2e18c6441b246989b0aebbe755b544b47e2e702
// Generated: 2026-04-18T21:11:11Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Credential, CredentialList, CredentialCreateRequest, CredentialPatchRequest } from './credential';

export class CredentialAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    return '/projects/{id}/credentials'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: CredentialCreateRequest, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<CredentialList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<CredentialList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: CredentialPatchRequest, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Credential> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
