// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: e075948095ee35d154a54e2d77a597f4fe48ef50e84ce30baeb5bc3f2bc2025a
// Generated: 2026-03-11T15:04:40Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectSettings = ObjectReference & {
  group_access: string;
  project_id: string;
  repositories: string;
};

export type ProjectSettingsList = ListMeta & {
  items: ProjectSettings[];
};

export type ProjectSettingsCreateRequest = {
  group_access?: string;
  project_id: string;
  repositories?: string;
};

export type ProjectSettingsPatchRequest = {
  group_access?: string;
  project_id?: string;
  repositories?: string;
};

export class ProjectSettingsBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  build(): ProjectSettingsCreateRequest {
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProjectSettingsCreateRequest;
  }
}

export class ProjectSettingsPatchBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  build(): ProjectSettingsPatchRequest {
    return this.data as ProjectSettingsPatchRequest;
  }
}
