// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 97773951f427a0271532ec5ed2e18c6441b246989b0aebbe755b544b47e2e702
// Generated: 2026-04-18T21:11:11Z

import type { ObjectReference, ListMeta } from './base';

export type RoleBinding = ObjectReference & {
  role_id: string;
  scope: string;
  scope_id: string;
  user_id: string;
};

export type RoleBindingList = ListMeta & {
  items: RoleBinding[];
};

export type RoleBindingCreateRequest = {
  role_id: string;
  scope: string;
  scope_id?: string;
  user_id: string;
};

export type RoleBindingPatchRequest = {
  role_id?: string;
  scope?: string;
  scope_id?: string;
  user_id?: string;
};

export class RoleBindingBuilder {
  private data: Record<string, unknown> = {};


  roleId(value: string): this {
    this.data['role_id'] = value;
    return this;
  }

  scope(value: string): this {
    this.data['scope'] = value;
    return this;
  }

  scopeId(value: string): this {
    this.data['scope_id'] = value;
    return this;
  }

  userId(value: string): this {
    this.data['user_id'] = value;
    return this;
  }

  build(): RoleBindingCreateRequest {
    if (!this.data['role_id']) {
      throw new Error('role_id is required');
    }
    if (!this.data['scope']) {
      throw new Error('scope is required');
    }
    if (!this.data['user_id']) {
      throw new Error('user_id is required');
    }
    return this.data as RoleBindingCreateRequest;
  }
}

export class RoleBindingPatchBuilder {
  private data: Record<string, unknown> = {};


  roleId(value: string): this {
    this.data['role_id'] = value;
    return this;
  }

  scope(value: string): this {
    this.data['scope'] = value;
    return this;
  }

  scopeId(value: string): this {
    this.data['scope_id'] = value;
    return this;
  }

  userId(value: string): this {
    this.data['user_id'] = value;
    return this;
  }

  build(): RoleBindingPatchRequest {
    return this.data as RoleBindingPatchRequest;
  }
}
