// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: e075948095ee35d154a54e2d77a597f4fe48ef50e84ce30baeb5bc3f2bc2025a
// Generated: 2026-03-11T15:04:40Z

import type { ObjectReference, ListMeta } from './base';

export type User = ObjectReference & {
  email: string;
  name: string;
  username: string;
};

export type UserList = ListMeta & {
  items: User[];
};

export type UserCreateRequest = {
  email?: string;
  name: string;
  username: string;
};

export type UserPatchRequest = {
  email?: string;
  name?: string;
  username?: string;
};

export class UserBuilder {
  private data: Record<string, unknown> = {};


  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['username']) {
      throw new Error('username is required');
    }
    return this.data as UserCreateRequest;
  }
}

export class UserPatchBuilder {
  private data: Record<string, unknown> = {};


  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserPatchRequest {
    return this.data as UserPatchRequest;
  }
}
